### ISSUE TITLE
Redundant line: var timestamp = reader.GetInt64(TimestampIndex);

### ISSUE THREAD

**Issue by OnurGumus** [ismaelhamed/akka.persistence.oracle#1]
https://github.com/ismaelhamed/akka.persistence.oracle/blob/master/src/Akka.Persistence.Oracle/Journal/OracleQueryExecutor.cs line 182 is not used. 

 
var timestamp = reader.GetInt64(TimestampIndex);

Possible bug ?

**Comment by ismaelhamed** [comment]
You are right, IPersistentRepresentation doesn't use the timestamp so there's no point in reading it (I brought this from Akka.Persistence.Sql.Common).
