### ISSUE TITLE
Why there is no index or PK on Ordering column?

### ISSUE THREAD

**Issue by OnurGumus** [ismaelhamed/akka.persistence.oracle#2]
I noticed there is no PK or index in the Ordering Column, which is not the same as SQL Server version is there a reason for this ?

**Comment by OnurGumus** [comment]
Because I was using an old version

**Comment by ismaelhamed** [comment]
@OnurGumus you're right on the money, thanks for pointing it out! The Ordering column is missing the PK. I've checked, and we do have a PK in production, so I must have screwed up along the way in this repo.

I'll add it, so that it's available for everyone starting v1.3.10
