### ISSUE TITLE
move or fork to odp.net core

### ISSUE THREAD

**Issue by OnurGumus** [ismaelhamed/akka.persistence.oracle#4]
odp.net.core now supports .net standart. I believe it is a good idea to move to odp.net core or fork the project.

**Comment by ismaelhamed** [comment]
I've been working on the [netstandard](https://github.com/ismaelhamed/akka.persistence.oracle/tree/netstandard) branch for a while now, and I just pushed the latest in case you want to try it.

Honestly, I don't want to maintain two separate libraries (netstandard2.0 and net45) nor I want to force anyone to move to .NET 4.6.1 or beyond (Akka itself still compiles against 4.5, so it's fair that any plugin does the same). So I'll probably stick to my original plan of waiting for Akka 1.4 to make the definitely move.

**Comment by OnurGumus** [comment]
@ismaelahmed, I think the time has come for this.

**Comment by ismaelhamed** [comment]
@OnurGumus almost there. I just pushed `1.4.0-beta1` to nuget.

**Comment by ismaelhamed** [comment]
Just pushed `v1.4.0-beta2`

**Comment by ismaelhamed** [comment]
Just pushed `v1.4.0-beta4`

**Comment by ismaelhamed** [comment]
Done.
